### ISSUE TITLE
For Android Studio 3.1,  on Linux, I need to create a  keymaps directory  manually inside config directory

### ISSUE THREAD

**Issue by fffx** [ekaragodin/idea-sublime-keymap#10]

**Comment by gornostal** [comment]
Hi @fffx,

Could you explain a bit more how you imported Sublime.xml for Android Studio?
What's the full path to Sublime.xml?

**Comment by fffx** [comment]
@gornostal 
I try to put  `Sublime.xml` to `$HOME/.AndroidStudio<version>/config/keymaps` folder, but for android-studio-3.1  on Linux(Ubuntu) the `keymaps` subfolder doesn't exist, so I created one, and  put   `Sublime.xml` in it.

**Comment by gornostal** [comment]
@fffx thanks
That worked
