### ISSUE TITLE
No multi-cursor selection Ctrl+Shift+Up/Down?

### ISSUE THREAD

**Issue by benwinding** [ekaragodin/idea-sublime-keymap#13]
Love the extension, but the most used feature of sublime (for me) is not in this keymap.

![multi cursor](https://i.imgur.com/V88X9Zd.png)

Multi-cursor selection has been possible in IntelliJ since 2014, is it possible to put this into this KeyMap to match the sublime keymapping of Ctrl+Shift+Up/Down?

**Comment by benwinding** [comment]
Ok, this seems to be a Linux thing...

In _Sublime Text 3_ `Ctrl+Shift+Up/Down` works as expected, but in _Idea_ the OS shortcuts interfere with this, so I need to choose another shortcut, unless someone else has a solution (to keep my OS shortcuts!)? :disappointed:

**Comment by neaucode** [comment]
In Sublime, I would select a common aspect of where the cursors will go eg `trip_` or the `\n` newline, then press CMD+D repeatedly to select all or once followed by CMD+U to undo, then use CMD+G to jump between them all and type differing part (1, 2, 3, 4, etc). Not sure this is what you're looking for though
