### ISSUE TITLE
Implement for pyCharm 2016

### ISSUE THREAD

**Issue by blomdahldaniel** [ekaragodin/idea-sublime-keymap#3]
Hi!
Seems to be great stuff!

Do you guys know how to use this in pyCharm 2016?

**Comment by ekaragodin** [comment]
Copy Sublime.xml to keymaps folder and activate in settings https://www.jetbrains.com/help/pycharm/2016.1/configuring-keyboard-shortcuts.html

**Comment by blomdahldaniel** [comment]
Thank you
